size:
  width: 900
  height: 720
count: 500
inputList: list.txt
outputList: list.out.txt
screenshots: screenshots/screenshots-1
excludes:
  - bp.blogspot.com
  - googleusercontent.com
  - adobe.com
  - amazon.co.jp
